drop table student;
drop table course;

CREATE TABLE STUDENT
(ID int identity(1,1) primary key,
NAME VARCHAR(30),
DOB date constraint dateofbirth check (DOB <'01-01-2019'));

CREATE TABLE COURSE
(COURSE_ID INT PRIMARY KEY,
COURSE_NAME VARCHAR(30),
DURATION FLOAT,
FEES FLOAT);


insert into COURSE values(1,'DataScience',2,29000)
insert into STUDENT values(1,'varsha','2000-sep-20')
insert into COURSE values(2,'DSA',9,90000)

select * from STUDENT 

CREATE OR ALTER PROCEDURE ENROLL
AS
BEGIN
SELECT * FROM STUDENT S JOIN COURSE C
 ON S.ID = C.COURSE_ID
 END
 EXEC ENROLL

 select EID,S.*,C.* FROM STUDENT_ENROLL E JOIN STUDENT S ON E.EID = S.ID JOIN 
 COURSE C ON C.COURSE_ID =E.ID

SELECT E.EID, S.*,C.* FROM STUDENT_ENROLL E JOIN STUDENT S ON E.ID = S.ID JOIN COURSE C ON E.COURSE_ID =C.COURSE_ID

CREATE TABLE STUDENT_ENROLL
(EID int identity(1,1) primary key,
ID INT FOREIGN KEY REFERENCES STUDENT(ID) UNIQUE,
COURSE_ID INT FOREIGN KEY REFERENCES COURSE(COURSE_ID))

select * from STUDENT_ENROLL

DROP TABLE STUDENT_ENROLL

INSERT INTO STUDENT_ENROLL VALUES(1,'VARSHA',1,'DATASCIENCE',5,29000)

INSERT INTO STUDENT_ENROLL VALUES(1,2)